version: '3.8'

services:
  ml-app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=prod
    volumes:
      - .:/app
    command: /root/.cargo/bin/uv run uvicorn app:app --host 0.0.0.0 --port 8000 --reload